name: polyexplore
channels:
  - snowflake
dependencies:
  - python=3.11
  - streamlit=1.36.0
  - rdkit
  - pandas=2.2.2
  - numpy=2.1.3
  - matplotlib=3.9.2
  - seaborn=0.13.2
  - openpyxl=3.1.5
  - scikit-learn=1.5.2
  - pillow=10.4.0

